[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=5MB

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx_out.log
stderr_logfile=/var/log/nginx_err.log

[program:node]
command=node /app/server.js
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/node_out.log
stderr_logfile=/var/log/node_err.log
